### ISSUE TITLE
--substitutions is broken in gcloud v201

### ISSUE THREAD

**Issue by pierrre** [GoogleCloudPlatform/container-builder-local#66]
(I'm sorry if it's not the correct way to report bug for this tool.)

In the latest gcloud v201, the `--substitutions` flag doesn't work anymore for `container-builder-local`.
It displays errors like this:
```
2018/05/17 17:02:30 Error validating build: key in the template "_VERSION" is not matched in the substitution data;key in the template "_VERSION" is not matched in the substitution data;key in the template "_VERSION" is not matched in the substitution data
```

I don't have any issue with gcloud v200.

**Comment by pierrre** [comment]
PS: it seems that the components was updated from `0.2.7` to `0.3.1`

**Comment by pierrre** [comment]
Actually it's maybe not a bug.
It seems that `where the key is already defined in the build request` was added in the help message.

I was using the previous behavior in order to ensure that the substitutions are always provided in the command line.

**Comment by Philmod** [comment]
Could you share a snippet of the config? And the command you use to start the build?

**Comment by pierrre** [comment]
```yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'image'
      - 'build'
      - '--build-arg'
      - 'VERSION=${_VERSION}'
      - '--tag'
      - 'gcr.io/${PROJECT_ID}/xxx:latest'
      - '--tag'
      - 'gcr.io/${PROJECT_ID}/xxx:${_VERSION}'
      - '.'
images:
  - 'gcr.io/${PROJECT_ID}/xxx:latest'
  - 'gcr.io/${PROJECT_ID}/xxx:${_VERSION}'
```
